<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.fuin.objects4j</groupId>
        <artifactId>objects4j-parent</artifactId>
        <version>0.12.0-SNAPSHOT</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>objects4j-bom</artifactId>
    <packaging>pom</packaging>

    <description>Bill of Materials (BOM) that manages the versions of all objects4j modules.</description>

    <dependencyManagement>

        <dependencies>

            <dependency>
                <groupId>org.fuin.objects4j</groupId>
                <artifactId>objects4j-common</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>org.fuin.objects4j</groupId>
                <artifactId>objects4j-core</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>org.fuin.objects4j</groupId>
                <artifactId>objects4j-crypto</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>org.fuin.objects4j</groupId>
                <artifactId>objects4j-jaxb</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>org.fuin.objects4j</groupId>
                <artifactId>objects4j-jackson</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>org.fuin.objects4j</groupId>
                <artifactId>objects4j-jpa</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>org.fuin.objects4j</groupId>
                <artifactId>objects4j-jsonb</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>org.fuin.objects4j</groupId>
                <artifactId>objects4j-ui</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>org.fuin.objects4j</groupId>
                <artifactId>objects4j-junit</artifactId>
                <version>${project.version}</version>
            </dependency>

        </dependencies>

    </dependencyManagement>

</project>
